question1 = ['\fontsize{14}Welcome to the power quality disturbs EXPLORER & CREATOR.',...
            sprintf('\n'), 'Is this your first use of the app ?'];
answer_1 = questdlg(question1, ... 
                  'Welcome!', ...
                  'Yes','No',...
                   struct('Default','','Interpreter','tex')); 
% Handle response
if strcmp(answer1,'No')
    display('return');
else
    question2 = ['\fontsize{14}Would you like a short explanation ?'];
    answer_2 = questdlg(question2, ...
                        'Welcome!', ...
                        'Yes','No',...
                        struct('Default','','Interpreter','tex'));
    if strcmp(answer2,'Yes')
       a=1; %call gui manual
    else
      a=2;  %show all buttons
    end
    
end
